menu/database/models/menu.py
from datetime import datetime
import pytz


class Menu:

    def __init__(self, recipes, week=None, year=None):
        dt = datetime.now(tz=pytz.timezone('Europe/Brussels'))
        self.year = year
        if not year:
            self.year = dt.year
        self.week = week
        if not week:
            self.week = dt.strftime('%W')
        self.recipes = {}
        self.add_recipes(recipes)

    def add_recipes(self, recipes):
        if type(recipes) != type(dict):
            recipes = [recipes]
        for day, recipe in recipes.items():
            self.recipes[day] = recipe

menu/database/models/recipe.py
class Recipe:

    def __init__(self, name, recipe, ingredients=(), rating=None):
        self.__recipe = {}
        self.name = name
        self.recipe = recipe
        self.ingredients = ingredients
        self.rating = rating

    def __mk(self):
        self.__recipe['name'] = self.name
        self.__recipe['recipe'] = self.recipe
        self.__recipe['ingredients'] = self.ingredients
        self.__recipe['rating'] = self.rating

    def db_obj(self):
        self.__mk()
        return self.__recipe

    def api_obj(self):
        self.__mk()
        return self.__recipe

menu/database/models/week.py
class Week:

    def __init__(self):
        pass

menu/routes.py
from flask import Blueprint, render_template
from flask_login import login_required
from datetime import datetime


gui = Blueprint('gui', __name__)


@gui.route('/', methods=['GET'])
def index():
    return render_template('index.html')


@gui.route('/week', methods=['GET'])
@gui.route('/week/<string:week>', methods=['GET'])
def week_overview(week=None):
    if not week:
        week = datetime.now().strftime('%U')
    return render_template('weekmenu/week.html', week=week, title='Week {0}'.format(week))


@gui.route('/recipe/<string:recipe_id>', methods=['GET'])
def recipe(recipe_id):
    return render_template('weekmenu/recipe.html', recipe_id=recipe_id, title='Recept')

templates/index.html
{% extends 'layout/base.html' %}

{% block content %}

    <!-- Page Header -->
    <header class="masthead"
            style="background-image: url('{{ url_for('static', filename='img/template/home-bg.jpg') }}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <span class="subheading">A Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 24, 2019</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of
                            mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 18, 2019</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on August 24, 2019</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future
                            generations.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on July 8, 2019</p>
                </div>
                <hr>
                <!-- Pager -->
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
                </div>
            </div>
        </div>
    </div>

    <hr>

{% endblock %}

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% if title %}{{ title }}{% else %}Weekmenu{% endif %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='js/template/vendor/bootstrap/css/bootstrap.min.css') }}"
          rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('static', filename='css/template/vendor/fontawesome-free/css/all.min.css') }}"
          rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/template/clean-blog.min.css') }}" rel="stylesheet">

    <!-- Custom stylesheet -->
    <link href="{{ url_for('static', filename='css/weekmenu.css') }}" rel="stylesheet">
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="index.html">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('gui.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('gui.week_overview') }}">Deze week</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Beheer</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Main Content -->
{% block content %}
{% endblock %}
<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{{ url_for('static', filename='js/template/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Custom scripts for this template -->
<script src="{{ url_for('static', filename='js/template/clean-blog.min.js') }}"></script>

</body>

</html>

templates/weekmenu/recipe.html
{% extends 'layout/base.html' %}
{% block content %}
<!-- Page Header -->
      <header class="masthead masthead-page">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-heading">
                        <h1>Erwtjes met worteltjes</h1>
                        <h2 class="subheading">Zaterdag</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

        </div>
      </div>
    </div>
  </article>
{% endblock %}

templates/weekmenu/week.html
{% extends 'layout/base.html' %}
{% block content %}
    <header class="masthead masthead-page">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-heading">
                        <h1>Week <span id="current_week">{{ week }}</span></h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
                    <a href="">
                        <h2 class="post-title">
                            Worst met erwtjes en worteltjes
                        </h2>
                        <h3 class="post-subtitle">
                            Zaterdag
                        </h3>
                    </a>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="">
                        <h2 class="post-title">
                            Worst met erwtjes en worteltjes
                        </h2>
                        <h3 class="post-subtitle">
                            Zondag
                        </h3>
                    </a>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="">
                        <h2 class="post-title">
                            Worst met erwtjes en worteltjes
                        </h2>
                        <h3 class="post-subtitle">
                            Maandag
                        </h3>
                    </a>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="">
                        <h2 class="post-title">
                            Worst met erwtjes en worteltjes
                        </h2>
                        <h3 class="post-subtitle">
                            Dinsdag
                        </h3>
                    </a>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="">
                        <h2 class="post-title">
                            Worst met erwtjes en worteltjes
                        </h2>
                        <h3 class="post-subtitle">
                            Woensdag
                        </h3>
                    </a>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="">
                        <h2 class="post-title">
                            Worst met erwtjes en worteltjes
                        </h2>
                        <h3 class="post-subtitle">
                            Donderdag
                        </h3>
                    </a>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="">
                        <h2 class="post-title">
                            Worst met erwtjes en worteltjes
                        </h2>
                        <h3 class="post-subtitle">
                            Vrijdag
                        </h3>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}